# Hexo Theme Fluid 配置
# 指南: https://hexo.fluid-dev.com/docs/guide/

navbar:
  blog_title: "Startale的博客"
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill", name: "文章" }
    - { key: "problems", link: "/problems/", icon: "iconfont icon-books", name: "题们" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category-fill", name: "分类" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }

banner:
  random_img: false
  parallax: true
  width_height_ratio: 0

index:
  banner_img:
  slogan:
    enable: true
    text: "行到水穷处，坐看云起时"

custom_js: /js/custom.js
custom_css: /css/custom.css

post:
  banner_img:
  banner_img_height: 70
  math:
    enable: true
    specific: false
    engine: mathjax

archive:
  banner_img:
  title: 文章

category:
  banner_img:
  title: 分类

tag:
  banner_img:

about:
  enable: true
  banner_img:
  avatar: /img/avatar.png
  name: "Startale803"
  intro: "一个普通的开发者"

page:
  banner_img:

page404:
  enable: true
  banner_img:

dark_mode:
  enable: true
  default: auto

footer:
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
  '
